baseURL: "https://youcan-jpn.github.io"
title: Yuta Ono
languageCode: ja
paginate: 5
theme: papermod

defaultContentLanguage: ja
languages:
  ja:
    languageName: 日本語
    weight: 1
    menu:
      main:
        - identifier: profile
          name: プロフィール
          url: /profile/
          weight: 10
        - identifier: research
          name: 研究
          url: /research/
          weight: 15
        - identifier: posts
          name: 投稿
          url: /posts/
          weight: 20
        - identifier: notes
          name: 雑記帳
          url: /notes/
          weight: 25
  en:
    languageName: English
    weight: 2
    menu:
      main:
        - identifier: profile
          name: Profile
          url: /profile/
          weight: 10
        - identifier: research
          name: Research
          url: /research/
          weight: 15
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 20
        - identifier: notes
          name: Notes
          url: /notes/
          weight: 25

params:
  env: production
  defaultTheme: auto
  math: true

  assets:
    disableHLJS: true
    favicon: "favicons/favicon.ico"
    favicon16x16:  "favicons/favicon-16x16.png"
    favicon32x32:  "favicons/favicon-32x32.png"
    apple_touch_icon:  "favicons/apple-touch-icon.png"

  profileMode:
      enabled: true
      subtitle: "Pursuing a Master's degree @[UTokyo](https://www.u-tokyo.ac.jp/en/index.html)"
      imageUrl: "favicons/yo-logo.png"
      imageTitle: "my icon"
      imageWidth: 200
      imageHeight: 200

  socialIcons:
      - name: "github"
        url: "https://github.com/youcan-jpn"

  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  description: Website of Yuta Ono
  images:
    - opengraph.png

output:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: true
    style: monokai

googleAnalytics: "G-N8937T99H2"
